name: Build qBittorrent Installer

on:
  workflow_dispatch: # Allows manual trigger from GitHub Actions tab

jobs:
  build:
    runs-on: windows-latest # Use a Windows runner for Windows installer

    steps:
      - name: Checkout qBittorrent Repository
        uses: actions/checkout@v4
        with:
          repository: 'qbittorrent/qBittorrent' # Specify the original qBittorrent repo
          ref: 'master' # Or any specific branch/tag you want to build (e.g., 'release-4.6.4')
          path: qBittorrent # Checkout into a specific directory

      - name: Set up MSVC environment
        uses: ilammy/msvc-dev-cmd@v1 # Initializes the Visual Studio development environment variables

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Use a recent Python 3 version

      - name: Cache vcpkg dependencies
        uses: actions/cache@v4
        id: vcpkg-cache
        with:
          path: D:\a\qBittorrent\qBittorrent/vcpkg_repo/installed # Cache the installed packages
          key: ${{ runner.os }}-vcpkg-${{ hashFiles('D:\a\qBittorrent\qBittorrent\vcpkg.json') }} # Key based on OS and vcpkg manifest

      - name: Install vcpkg dependencies
        shell: pwsh
        run: |
          $VCPKG_REPO_DIR = "D:\a\qBittorrent\qBittorrent/vcpkg_repo"
          New-Item -ItemType Directory -Force -Path $VCPKG_REPO_DIR

          if (-not (Test-Path "$VCPKG_REPO_DIR\.git")) {
            Write-Host "Cloning vcpkg into $VCPKG_REPO_DIR..."
            git clone https://github.com/microsoft/vcpkg.git $VCPKG_REPO_DIR
          } else {
            Write-Host "vcpkg repository already exists, skipping clone."
          }

          cd $VCPKG_REPO_DIR
          Write-Host "Bootstrapping vcpkg..."
          .\bootstrap-vcpkg.bat # Or bootstrap-vcpkg.sh for Linux/macOS

          Write-Host "Installing vcpkg dependencies for qBittorrent..."
          # Install dependencies based on qBittorrent's vcpkg.json
          # Note: Adjust triplet if building for a different target (e.g., x86-windows-static)
          # We're using x64-windows-static as per qBittorrent's build instructions for official builds
          .\vcpkg.exe install --triplet x64-windows-static --recurse --x-set-installed D:\a\qBittorrent\qBittorrent # Use qBittorrent's vcpkg.json

      - name: Manually Build and Install libtorrent
        shell: pwsh
        env:
          VCPKG_REPO_DIR: D:\a\qBittorrent\qBittorrent/vcpkg_repo
          LIBTORRENT_SOURCE_DIR: D:\a\qBittorrent\qBittorrent/libtorrent_source
          LIBTORRENT_INSTALL_DIR: D:\a\qBittorrent\qBittorrent/libtorrent_install
        run: |
          Write-Host "Preparing for manual libtorrent build."

          # Create directories
          New-Item -ItemType Directory -Force -Path $env:LIBTORRENT_SOURCE_DIR
          New-Item -ItemType Directory -Force -Path $env:LIBTORRENT_INSTALL_DIR

          # Clone libtorrent repository
          if (-not (Test-Path "$env:LIBTORRENT_SOURCE_DIR\.git")) {
            Write-Host "Cloning libtorrent into $env:LIBTORRENT_SOURCE_DIR..."
            git clone https://github.com/arvidn/libtorrent.git $env:LIBTORRENT_SOURCE_DIR
          } else {
            Write-Host "Libtorrent source directory already exists, skipping clone."
          }

          cd $env:LIBTORRENT_SOURCE_DIR
          Write-Host "Checking out RC_2_0 branch for libtorrent (newer series)..."
          # If you need libtorrent 1.2.x series, change 'RC_2_0' to 'RC_1_2'
          git checkout RC_2_0
          git pull # Ensure it's up-to-date with the chosen branch

          # --- FIX: Initialize and update submodules ---
          Write-Host "Initializing and updating libtorrent submodules..."
          git submodule update --init --recursive
          # ---------------------------------------------

          Write-Host "Configuring libtorrent with CMake..."
          cmake -G "Ninja" -B build `
            -DCMAKE_BUILD_TYPE=Release `
            -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_REPO_DIR\scripts\buildsystems\vcpkg.cmake" `
            -DVCPKG_TARGET_TRIPLET="x64-windows-static" `
            -DBUILD_SHARED_LIBS=OFF `
            -Dstatic_runtime=ON `
            -Ddeprecated-functions=ON # Enable for wider compatibility with qBittorrent
          Write-Host "Libtorrent configuration complete."

          Write-Host "Building libtorrent..."
          cmake --build build --config Release
          Write-Host "Libtorrent build complete."

          Write-Host "Installing libtorrent to $env:LIBTORRENT_INSTALL_DIR..."
          cmake --install build --prefix $env:LIBTORRENT_INSTALL_DIR
          Write-Host "Libtorrent installation complete."

          # Output the libtorrent install path for the next step
          echo "LIBTORRENT_INSTALL_DIR_OUTPUT=$env:LIBTORRENT_INSTALL_DIR" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

      - name: Build qBittorrent
        shell: pwsh
        env:
          LIBTORRENT_INSTALL_DIR_FROM_PREV: ${{ steps.libtorrent_build.outputs.LIBTORRENT_INSTALL_DIR_OUTPUT }} # Get path from previous step
          VCPKG_ROOT: D:\a\qBittorrent\qBittorrent/vcpkg_repo # Set VCPKG_ROOT for qBittorrent build
          VCPKG_TARGET_TRIPLET: x64-windows-static # Specify triplet for qBittorrent build
          QB_BUILD_DIR: D:\a\qBittorrent\qBittorrent/build_qbittorrent
        run: |
          Write-Host "Configuring qBittorrent with CMake..."
          # Set LIBTORRENT_INSTALL_DIR as an environment variable for qBittorrent's CMake
          # Or pass it directly via -D, depending on how qBittorrent's CMake expects it
          # qBittorrent often uses FIND_PACKAGE(libtorrent) which will look in VCPKG_ROOT
          # and possibly CMAKE_PREFIX_PATH. Let's ensure CMAKE_PREFIX_PATH includes our custom install
          $env:CMAKE_PREFIX_PATH = "$env:LIBTORRENT_INSTALL_DIR_FROM_PREV;$env:CMAKE_PREFIX_PATH"

          cd D:\a\qBittorrent\qBittorrent

          cmake -G "Ninja" -B $env:QB_BUILD_DIR `
            -DCMAKE_BUILD_TYPE=Release `
            -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_ROOT\scripts\buildsystems\vcpkg.cmake" `
            -DVCPKG_TARGET_TRIPLET=$env:VCPKG_TARGET_TRIPLET `
            -DBOOST_ASIO_USE_IOCP=ON `
            -DQT_STATIC_BUILD=ON `
            -DQT_LTCG=ON `
            -DLIBTP_QT=ON `
            -DBUILD_GUI=ON `
            -DWEBUITESTS=OFF `
            -DSTACK_PROTECTOR=ON `
            -DQT_VERSION=6 # Specify Qt6 for newer builds
          Write-Host "qBittorrent configuration complete."

          Write-Host "Building qBittorrent..."
          cmake --build $env:QB_BUILD_DIR --config Release
          Write-Host "qBittorrent build complete."

      - name: Generate Inno Setup Installer
        shell: pwsh
        env:
          QB_BUILD_DIR: D:\a\qBittorrent\qBittorrent/build_qbittorrent
          QB_VERSION: master # Or extract from qBittorrent source if desired
        run: |
          Write-Host "Generating Inno Setup Installer..."
          # Inno Setup is pre-installed on windows-latest runners

          # Define installer output path
          $installerOutput = "$env:GITHUB_WORKSPACE/qbittorrent_installer.exe"

          # Run the Inno Setup script.
          # qBittorrent's source contains an Inno Setup script in the 'dist' directory.
          # We need to pass the build directory to it.
          # Find the Inno Setup executable. It's usually in C:\Program Files (x86)\Inno Setup 6\ISCC.exe
          $innoSetupExe = "C:\Program Files (x86)\Inno Setup 6\ISCC.exe"

          if (-not (Test-Path $innoSetupExe)) {
              throw "Inno Setup compiler not found at $innoSetupExe"
          }

          # The Inno Setup script likely expects the build directory as a parameter or an environment variable.
          # We'll use a common approach: passing defines to ISCC.exe
          # Adjust the path to the qBittorrent dist/qBittorrent.iss if necessary based on the repo structure
          $issFile = "D:\a\qBittorrent\qBittorrent\dist\qBittorrent.iss"
          if (-not (Test-Path $issFile)) {
              throw "qBittorrent Inno Setup script not found at $issFile"
          }

          # Define the output directory for the installer within the runner's workspace
          $InstallerOutputDir = "$env:GITHUB_WORKSPACE/installers"
          New-Item -ItemType Directory -Force -Path $InstallerOutputDir

          # Execute Inno Setup compiler
          & "$innoSetupExe" /o"$InstallerOutputDir" /dVERSION="$env:QB_VERSION" /dBUILD_DIR="$env:QB_BUILD_DIR" /dOUTPUT_BASE_NAME="qbittorrent_v${env:QB_VERSION}_x64_setup" "$issFile"
          Write-Host "Installer generation complete."

      - name: Upload Installer Artifact
        uses: actions/upload-artifact@v4
        with:
          name: qBittorrent-Installer
          path: ${{ github.workspace }}/installers/*.exe # Adjust path if the installer name or location differs
          retention-days: 7 # Keep the artifact for 7 days
